# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROFILE_REACT_BASEADO_NA_BRANCH: ${{ fromJSON('{"main":"development","develop":"development"}')[github.ref_name] }}
      SUFIXO_ENV_BASEADO_NA_BRANCH: ${{ fromJSON('{"main":"_PROD","develop":"_DEV"}')[github.ref_name] }}
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Checando versão yarn
        run: yarn --version

      - name: Branch atual
        run: echo $GITHUB_REF_NAME

      - name: Profile react a ser utilizado
        run: echo $PROFILE_REACT_BASEADO_NA_BRANCH

      - name: Sufixo para buscar secrets
        run: echo $SUFIXO_ENV_BASEADO_NA_BRANCH

      - name: Definindo nome dos secrets
        run: |
          echo "SUPER_SECRETO_SECRET_NAME=SUPER_SECRETO${{ env.SUFIXO_ENV_BASEADO_NA_BRANCH }}" >> $GITHUB_ENV
          echo "Tentando imprimir GITHUB ENV"
          echo $GITHUB_ENV

      - name: Usando o valor dos secrets (pre-ri-go)
        env:
          SUPER_SECRETO_VALOR: ${{ secrets[env.SUPER_SECRETO_SECRET_NAME] }}
        run: |
          echo "O nome do segredo é ${{env.SUPER_SECRETO_SECRET_NAME}}"
          echo "Adicionando o valor do Secret dentro de TESTE"
          echo TESTE=$SUPER_SECRETO_VALOR
          echo $TESTE
          echo "Salvando o valor do segredo em arquivo"          
          printf $SUPER_SECRETO_VALOR >> src/teste.txt
          echo $SUPER_SECRETO_VALOR >> src/teste.txt
          echo "xpto" >> src/teste.txt
          echo "Imprimindo valor do segredo"
          cat src/teste.txt

      - name: Instalando dependencias
        run: yarn install --frozen-lockfile

      - name: Buildando a aplicação react com base na branch
        run: yarn build --profile $PROFILE_REACT_BASEADO_NA_BRANCH
